# -*- coding: utf-8 -*-
"""Untitled63.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kSO00TCHokRTpvc98WZ0csxzjsRJVES-
"""

# ============================================================
# xLab: Build Your First Image Encoder–Decoder
# Complete Colab-ready solution
# ============================================================

# If needed, uncomment:
# !pip install torch torchvision matplotlib

import torch
from torch import nn
from torch.utils.data import DataLoader, Subset
from torchvision import datasets, transforms
import matplotlib.pyplot as plt

# ------------------------------------------------------------
# 1. SETUP AND LOAD DATA
# ------------------------------------------------------------

torch.manual_seed(42)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

BATCH_SIZE = 64
EPOCHS = 5
LATENT_CHANNELS = 8

print("Device:", device)

train_data = datasets.MNIST(
    "./data",
    train=True,
    download=True,
    transform=transforms.ToTensor()
)

test_data = datasets.MNIST(
    "./data",
    train=False,
    download=True,
    transform=transforms.ToTensor()
)

# Fixed random subsets
g = torch.Generator().manual_seed(42)

train_data = Subset(
    train_data,
    torch.randperm(len(train_data), generator=g)[:5000].tolist()
)

test_data = Subset(
    test_data,
    torch.randperm(len(test_data), generator=g)[:1000].tolist()
)

train_loader = DataLoader(
    train_data,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=0
)

test_loader = DataLoader(
    test_data,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=0
)

images, labels = next(iter(train_loader))

print(
    "Batch:",
    tuple(images.shape),
    "Pixel range:",
    images.min().item(),
    images.max().item()
)

# Show sample images
fig, axes = plt.subplots(1, 8, figsize=(12, 2))

for ax, img in zip(axes, images[:8]):
    ax.imshow(img[0], cmap="gray", vmin=0, vmax=1)
    ax.axis("off")

plt.show()


# ------------------------------------------------------------
# 2. SHAPE CALCULATIONS
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("SHAPE CALCULATIONS")
print("=" * 60)

# Input: 28 x 28
#
# Conv2d formula:
# H_out = floor((H + 2P - D(K-1) - 1)/S + 1)
#
# Encoder 1:
# H = floor((28 + 2*1 - 1*(3-1) - 1)/2 + 1)
#   = 14
#
# Encoder 2:
# H = floor((14 + 2*1 - 2 - 1)/2 + 1)
#   = 7
#
# Bottleneck:
# kernel=1, stride=1, padding=0 -> remains 7x7
#
# Decoder:
# H_out = (H-1)*stride - 2*padding + kernel + output_padding
#       = (7-1)*2 - 2*1 + 3 + 1
#       = 14
#
# Second decoder:
#       = (14-1)*2 - 2*1 + 3 + 1
#       = 28

print("Input:       [N, 1, 28, 28]")
print("Encoder 1:  [N, 16, 14, 14]")
print("Encoder 2:  [N, 32, 7, 7]")
print(f"Bottleneck:  [N, {LATENT_CHANNELS}, 7, 7]")
print("Decoder 1:  [N, 16, 14, 14]")
print("Decoder 2:  [N, 1, 28, 28]")

input_values = 1 * 28 * 28

for L in [2, 8, 32]:
    latent_values = L * 7 * 7
    ratio = input_values / latent_values

    print(
        f"L={L}: "
        f"input values={input_values}, "
        f"latent values={latent_values}, "
        f"input/latent ratio={ratio:.4f}"
    )

print("\nAnswers:")
print("1. For L=8:")
print("   Input values per image = 784")
print("   Latent values = 8 * 7 * 7 = 392")
print("   Input/latent ratio = 784/392 = 2")

print("\n2. For L=32:")
print("   Latent values = 32 * 7 * 7 = 1568.")
print("   This is larger than the 784 input values, so it is NOT")
print("   dimensionally compressed relative to the input.")

print("\n3. Final Sigmoid is used because MNIST pixels are scaled")
print("   to [0, 1] by ToTensor().")

print("\n4. First decoder output with output_padding=0:")
print("   (7-1)*2 - 2*1 + 3 + 0 = 13")
print("   Therefore output height = 13.")


# ------------------------------------------------------------
# 3. ENCODER
# ------------------------------------------------------------

class Encoder(nn.Module):

    def __init__(self, latent_channels=8):
        super().__init__()

        # TODO 1 completed
        self.network = nn.Sequential(
            nn.Conv2d(
                in_channels=1,
                out_channels=16,
                kernel_size=3,
                stride=2,
                padding=1
            ),
            nn.ReLU(),

            nn.Conv2d(
                in_channels=16,
                out_channels=32,
                kernel_size=3,
                stride=2,
                padding=1
            ),
            nn.ReLU(),

            nn.Conv2d(
                in_channels=32,
                out_channels=latent_channels,
                kernel_size=1,
                stride=1,
                padding=0
            )
        )

    def forward(self, x):
        return self.network(x)


# ------------------------------------------------------------
# 4. DECODER
# ------------------------------------------------------------

class Decoder(nn.Module):

    def __init__(self, latent_channels=8):
        super().__init__()

        # TODO 2 completed
        self.network = nn.Sequential(

            nn.ConvTranspose2d(
                in_channels=latent_channels,
                out_channels=16,
                kernel_size=3,
                stride=2,
                padding=1,
                output_padding=1
            ),
            nn.ReLU(),

            nn.ConvTranspose2d(
                in_channels=16,
                out_channels=1,
                kernel_size=3,
                stride=2,
                padding=1,
                output_padding=1
            ),
            nn.Sigmoid()
        )

    def forward(self, z):
        return self.network(z)


# ------------------------------------------------------------
# 5. COMBINED ENCODER-DECODER
# ------------------------------------------------------------

class ImageEncoderDecoder(nn.Module):

    def __init__(self, latent_channels=8):
        super().__init__()

        self.encoder = Encoder(latent_channels)
        self.decoder = Decoder(latent_channels)

    def forward(self, x):

        # TODO 3 completed
        z = self.encoder(x)
        reconstruction = self.decoder(z)

        return reconstruction, z


# ------------------------------------------------------------
# 6. SHAPE AND RANGE CHECKS
# ------------------------------------------------------------

model = ImageEncoderDecoder(LATENT_CHANNELS).to(device)

x = torch.rand(
    4,
    1,
    28,
    28,
    device=device
)

with torch.no_grad():

    reconstruction, z = model(x)

assert z.shape == (
    4,
    LATENT_CHANNELS,
    7,
    7
), "Check encoder stride/padding/channels"

assert reconstruction.shape == x.shape, \
    "Check decoder output_padding"

assert torch.isfinite(reconstruction).all(), \
    "Output contains nonfinite values"

assert ((reconstruction >= 0) & (reconstruction <= 1)).all(), \
    "Check output activation"

print("\n" + "=" * 60)
print("SHAPE CHECK")
print("=" * 60)

print("Input:         ", tuple(x.shape))
print("Latent:        ", tuple(z.shape))
print("Reconstruction:", tuple(reconstruction.shape))

print("Shape and range checks passed!")


# ------------------------------------------------------------
# 7. TRAINING STEP
# ------------------------------------------------------------

criterion = nn.MSELoss()


def train_step(model, images, optimizer, criterion):

    # TODO 4 completed

    # Clear old gradients
    optimizer.zero_grad()

    # Forward pass
    reconstruction, z = model(images)

    # Reconstruction loss
    loss = criterion(reconstruction, images)

    # Backpropagation
    loss.backward()

    # Update parameters
    optimizer.step()

    # Return Python number
    return loss.item()


# ------------------------------------------------------------
# 8. EVALUATION
# ------------------------------------------------------------

@torch.no_grad()
def evaluate(model, loader):

    model.eval()

    total_loss = 0.0

    for images, _ in loader:

        images = images.to(device)

        reconstruction, _ = model(images)

        total_loss += (
            criterion(reconstruction, images).item()
            * images.size(0)
        )

    return total_loss / len(loader.dataset)


# ------------------------------------------------------------
# 9. TRAIN MODEL
# ------------------------------------------------------------

print("\n" + "=" * 60)
print(f"TRAINING AUTOENCODER - LATENT CHANNELS = {LATENT_CHANNELS}")
print("=" * 60)

torch.manual_seed(42)

model = ImageEncoderDecoder(
    LATENT_CHANNELS
).to(device)

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=1e-3
)

initial_mse = evaluate(
    model,
    test_loader
)

print(
    f"Untrained held-out MSE: {initial_mse:.5f}"
)

history = {
    "train": [],
    "test": []
}

for epoch in range(EPOCHS):

    model.train()

    total_loss = 0.0

    for images, _ in train_loader:

        images = images.to(device)

        total_loss += (
            train_step(
                model,
                images,
                optimizer,
                criterion
            )
            * images.size(0)
        )

    train_mse = (
        total_loss /
        len(train_loader.dataset)
    )

    test_mse = evaluate(
        model,
        test_loader
    )

    history["train"].append(train_mse)
    history["test"].append(test_mse)

    print(
        f"Epoch {epoch + 1}: "
        f"train MSE={train_mse:.5f}, "
        f"held-out MSE={test_mse:.5f}"
    )


# ------------------------------------------------------------
# 10. TRAINING CURVE
# ------------------------------------------------------------

plt.figure(figsize=(7, 5))

plt.plot(
    range(1, EPOCHS + 1),
    history["train"],
    marker="o",
    label="Train"
)

plt.plot(
    range(1, EPOCHS + 1),
    history["test"],
    marker="o",
    label="Held-out"
)

plt.xlabel("Epoch")
plt.ylabel("Mean squared error")
plt.title(
    f"Training Curve - Latent Channels = {LATENT_CHANNELS}"
)

plt.legend()
plt.grid(alpha=0.3)
plt.show()


# ------------------------------------------------------------
# 11. ORIGINAL VS RECONSTRUCTION
# ------------------------------------------------------------

model.eval()

examples, _ = next(iter(test_loader))

with torch.no_grad():

    reconstructed, latents = model(
        examples[:8].to(device)
    )

reconstructed = reconstructed.cpu()
latents = latents.cpu()

fig, axes = plt.subplots(
    2,
    8,
    figsize=(12, 4)
)

for i in range(8):

    axes[0, i].imshow(
        examples[i, 0],
        cmap="gray",
        vmin=0,
        vmax=1
    )

    axes[1, i].imshow(
        reconstructed[i, 0],
        cmap="gray",
        vmin=0,
        vmax=1
    )

    axes[0, i].axis("off")
    axes[1, i].axis("off")

axes[0, 0].set_ylabel(
    "Original",
    fontsize=12
)

axes[1, 0].set_ylabel(
    "Reconstructed",
    fontsize=12
)

fig.suptitle(
    "Original vs Reconstruction"
)

plt.tight_layout()
plt.show()


# ------------------------------------------------------------
# 12. VISUALIZE LATENT MAPS
# ------------------------------------------------------------

count = min(
    LATENT_CHANNELS,
    8
)

fig, axes = plt.subplots(
    1,
    count,
    figsize=(2 * count, 2),
    squeeze=False
)

for i in range(count):

    axes[0, i].imshow(
        latents[0, i],
        cmap="viridis"
    )

    axes[0, i].set_title(
        f"Channel {i}"
    )

    axes[0, i].axis("off")

fig.suptitle(
    "Latent maps of the first image"
)

plt.tight_layout()
plt.show()


# ------------------------------------------------------------
# 13. MODEL PARAMETER COUNT
# ------------------------------------------------------------

total_parameters = sum(
    p.numel()
    for p in model.parameters()
)

trainable_parameters = sum(
    p.numel()
    for p in model.parameters()
    if p.requires_grad
)

print("\n" + "=" * 60)
print("MODEL INFORMATION")
print("=" * 60)

print(
    f"Latent shape: "
    f"[N, {LATENT_CHANNELS}, 7, 7]"
)

print(
    f"Latent values/image: "
    f"{LATENT_CHANNELS * 7 * 7}"
)

print(
    f"Input values/image: "
    f"{28 * 28}"
)

print(
    f"Input/latent ratio: "
    f"{(28 * 28) / (LATENT_CHANNELS * 7 * 7):.4f}"
)

print(
    f"Total parameters: "
    f"{total_parameters:,}"
)

print(
    f"Trainable parameters: "
    f"{trainable_parameters:,}"
)


# ============================================================
# 14. BOTTLENECK EXPERIMENT: 2, 8, 32 CHANNELS
# ============================================================

print("\n" + "=" * 60)
print("BOTTLENECK EXPERIMENT")
print("=" * 60)

experiment_results = []

latent_values_list = [2, 8, 32]

for latent_channels in latent_values_list:

    print("\n" + "-" * 60)
    print(
        f"Running experiment: "
        f"LATENT_CHANNELS = {latent_channels}"
    )
    print("-" * 60)

    # Reset seed for repeatability
    torch.manual_seed(42)

    experiment_model = ImageEncoderDecoder(
        latent_channels
    ).to(device)

    experiment_optimizer = torch.optim.Adam(
        experiment_model.parameters(),
        lr=1e-3
    )

    experiment_history = {
        "train": [],
        "test": []
    }

    for epoch in range(EPOCHS):

        experiment_model.train()

        total_loss = 0.0

        for batch_images, _ in train_loader:

            batch_images = batch_images.to(device)

            loss = train_step(
                experiment_model,
                batch_images,
                experiment_optimizer,
                criterion
            )

            total_loss += (
                loss *
                batch_images.size(0)
            )

        train_mse = (
            total_loss /
            len(train_loader.dataset)
        )

        test_mse = evaluate(
            experiment_model,
            test_loader
        )

        experiment_history["train"].append(
            train_mse
        )

        experiment_history["test"].append(
            test_mse
        )

        print(
            f"Epoch {epoch + 1}: "
            f"train={train_mse:.5f}, "
            f"held-out={test_mse:.5f}"
        )

    latent_values = (
        latent_channels * 7 * 7
    )

    ratio = (
        28 * 28
    ) / latent_values

    final_train_mse = (
        experiment_history["train"][-1]
    )

    final_test_mse = (
        experiment_history["test"][-1]
    )

    params = sum(
        p.numel()
        for p in experiment_model.parameters()
    )

    experiment_results.append({
        "Latent Channels": latent_channels,
        "Latent Values": latent_values,
        "Input/Latent Ratio": ratio,
        "Final Train MSE": final_train_mse,
        "Final Held-out MSE": final_test_mse,
        "Parameters": params
    })

    # Show reconstructions for this experiment
    experiment_model.eval()

    with torch.no_grad():

        exp_reconstruction, _ = experiment_model(
            examples[:8].to(device)
        )

    exp_reconstruction = (
        exp_reconstruction.cpu()
    )

    fig, axes = plt.subplots(
        2,
        8,
        figsize=(12, 4)
    )

    for i in range(8):

        axes[0, i].imshow(
            examples[i, 0],
            cmap="gray",
            vmin=0,
            vmax=1
        )

        axes[1, i].imshow(
            exp_reconstruction[i, 0],
            cmap="gray",
            vmin=0,
            vmax=1
        )

        axes[0, i].axis("off")
        axes[1, i].axis("off")

    axes[0, 0].set_ylabel(
        "Original",
        fontsize=12
    )

    axes[1, 0].set_ylabel(
        "Reconstructed",
        fontsize=12
    )

    fig.suptitle(
        f"Latent Channels = {latent_channels}"
    )

    plt.tight_layout()
    plt.show()


# ------------------------------------------------------------
# 15. PRINT EXPERIMENT TABLE
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("BOTTLENECK EXPERIMENT RESULTS")
print("=" * 80)

print(
    f"{'Channels':<12}"
    f"{'Latent Values':<16}"
    f"{'Input/Latent':<16}"
    f"{'Train MSE':<16}"
    f"{'Held-out MSE':<16}"
    f"{'Parameters':<14}"
)

print("-" * 80)

for result in experiment_results:

    print(
        f"{result['Latent Channels']:<12}"
        f"{result['Latent Values']:<16}"
        f"{result['Input/Latent Ratio']:<16.4f}"
        f"{result['Final Train MSE']:<16.5f}"
        f"{result['Final Held-out MSE']:<16.5f}"
        f"{result['Parameters']:<14,}"
    )


# ------------------------------------------------------------
# 16. AUTOMATIC OBSERVATION HELPER
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("OBSERVATION GUIDE")
print("=" * 60)

for result in experiment_results:

    L = result["Latent Channels"]
    values = result["Latent Values"]
    ratio = result["Input/Latent Ratio"]
    train_mse = result["Final Train MSE"]
    test_mse = result["Final Held-out MSE"]

    print(
        f"\nL={L}: "
        f"{values} latent values/image, "
        f"compression ratio={ratio:.2f}, "
        f"train MSE={train_mse:.5f}, "
        f"held-out MSE={test_mse:.5f}"
    )

print("""
Use the reconstruction images together with the MSE values
for your discussion.

Key concepts:

1. A spatial latent has shape [N, L, 7, 7].
2. Downsampling reduces spatial resolution, but increasing the
   number of channels can offset or exceed that reduction.
3. The decoder learns to reconstruct likely image structure;
   it does not have to recover every original pixel exactly.
4. A [N, 128] latent is a flat vector. The [N, L, 7, 7] latent
   preserves spatial organization.
5. Skip connections could pass high-resolution encoder features
   directly to the decoder. This can make reconstruction easier
   while weakening the information bottleneck.
6. An autoencoder reconstructs images from its input. It is not
   automatically a reliable random-image generator because it
   has not been trained to map arbitrary random latent samples
   to realistic images.
""")


# ------------------------------------------------------------
# 17. OPTIONAL: SIMPLE MODEL ARCHITECTURE PRINT
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("FINAL MODEL ARCHITECTURE")
print("=" * 60)

print(model)


# ------------------------------------------------------------
# DONE
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("LAB COMPLETE!")
print("=" * 60)

print("""
You have completed:

[✓] Data loading
[✓] Shape calculations
[✓] Encoder
[✓] Spatial bottleneck
[✓] Decoder
[✓] Forward pass
[✓] Shape/range checks
[✓] Reconstruction MSE
[✓] Training loop
[✓] Held-out evaluation
[✓] Training curve
[✓] Original/reconstructed images
[✓] Latent visualization
[✓] Latent size calculations
[✓] 2/8/32 bottleneck experiment
""")