# -*- coding: utf-8 -*-
"""Untitled65.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ae5WZtebcbk2LHLHnvKdS8TpDTp8z9B6
"""

# ============================================================
# GAN LAB: FROM RANDOM DIGITS TO REQUESTED DIGITS
# Google Colab - Complete Code
# ============================================================

# Optional: install dependencies if needed
# !pip install -q torch torchvision matplotlib

from pathlib import Path
import gzip
import shutil
import json
import time
import random

import torch
from torch import nn
from torch.nn import functional as F
from torch.utils.data import DataLoader, Subset
from torchvision import datasets, transforms
from torchvision.utils import make_grid, save_image
import matplotlib.pyplot as plt


# ============================================================
# SETUP
# ============================================================

SEED = 42

LATENT_DIM = 100
NUM_CLASSES = 10
IMG_SIZE = 32
IMG_DIM = 28 * 28

BATCH_SIZE = 128
LR = 2e-4

BASELINE_EPOCHS = 10
CONDITIONAL_EPOCHS = 10

# First run can be True to check that everything works.
# For actual training, change to False.
SMOKE_TEST = True

# Optional smaller training subset for limited hardware.
# Example: TRAIN_LIMIT = 10000
TRAIN_LIMIT = None

# For normal Google Colab, leave this as None.
OFFLINE_MNIST_DIR = None


DEVICE = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

# Google Colab output directory
WORK_DIR = Path("/content")

DATA_DIR = WORK_DIR / "data"
OUTPUT_DIR = WORK_DIR / "gan_lab_student"

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def seed_all(seed):
    random.seed(seed)
    torch.manual_seed(seed)

    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


seed_all(SEED)

print("Device:", DEVICE)
print("Smoke mode:", SMOKE_TEST)
print("Outputs:", OUTPUT_DIR.resolve())


# ============================================================
# A. VANILLA GAN
# ============================================================

class VanillaGenerator(nn.Module):

    def __init__(
        self,
        latent_dim=LATENT_DIM,
        img_dim=IMG_DIM
    ):
        super().__init__()

        self.net = nn.Sequential(

            nn.Linear(latent_dim, 256),
            nn.LeakyReLU(0.2),

            nn.Linear(256, 512),
            nn.LeakyReLU(0.2),

            nn.Linear(512, 1024),
            nn.LeakyReLU(0.2),

            nn.Linear(1024, img_dim),

            nn.Tanh()
        )

    def forward(self, z):
        return self.net(z)


class VanillaDiscriminator(nn.Module):

    def __init__(self, img_dim=IMG_DIM):
        super().__init__()

        self.net = nn.Sequential(

            nn.Linear(img_dim, 512),
            nn.LeakyReLU(0.2),

            nn.Linear(512, 256),
            nn.LeakyReLU(0.2),

            nn.Linear(256, 1)
        )

    def forward(self, x):
        return self.net(x)


# BCEWithLogitsLoss because discriminator outputs logits
criterion = nn.BCEWithLogitsLoss()


def generate(g, z, labels=None):

    if labels is None:
        return g(z)

    return g(z, labels)


def discriminate(d, images, labels=None):

    if labels is None:
        return d(images)

    return d(images, labels)


# ============================================================
# TODO A1 - DISCRIMINATOR UPDATE
# ============================================================

def discriminator_step(
    g,
    d,
    opt_g,
    opt_d,
    real,
    labels=None
):

    g.train()
    d.train()

    # Clear discriminator gradients
    opt_d.zero_grad(set_to_none=True)

    # Generate fake images
    z = torch.randn(
        real.size(0),
        LATENT_DIM,
        device=real.device
    )

    fake = generate(g, z, labels)

    # IMPORTANT:
    # Detach fake images so gradients do not flow into G
    fake = fake.detach()

    # Real predictions
    real_logits = discriminate(
        d,
        real,
        labels
    )

    # Fake predictions
    fake_logits = discriminate(
        d,
        fake,
        labels
    )

    # Targets
    real_targets = torch.ones_like(real_logits)
    fake_targets = torch.zeros_like(fake_logits)

    # BCE losses
    real_loss = criterion(
        real_logits,
        real_targets
    )

    fake_loss = criterion(
        fake_logits,
        fake_targets
    )

    # Total discriminator loss
    loss = real_loss + fake_loss

    # Backpropagation
    loss.backward()

    # Update only discriminator
    opt_d.step()

    return loss.item()


# ============================================================
# TODO A2 - GENERATOR UPDATE
# ============================================================

def generator_step(
    g,
    d,
    opt_g,
    opt_d,
    batch_size,
    labels=None
):

    g.train()

    opt_g.zero_grad(set_to_none=True)
    opt_d.zero_grad(set_to_none=True)

    previous_mode = d.training

    # Freeze discriminator parameters
    d.requires_grad_(False)

    # Evaluation mode prevents BatchNorm statistics from changing
    d.eval()

    try:

        # Generate noise
        z = torch.randn(
            batch_size,
            LATENT_DIM,
            device=next(g.parameters()).device
        )

        # IMPORTANT:
        # Do NOT detach fake images here.
        # We need gradients through D back into G.
        fake = generate(
            g,
            z,
            labels
        )

        # Discriminator evaluates generated images
        fake_logits = discriminate(
            d,
            fake,
            labels
        )

        # Generator wants D to classify fake images as REAL
        targets = torch.ones_like(fake_logits)

        loss = criterion(
            fake_logits,
            targets
        )

        # Backpropagate through D into G
        loss.backward()

        # Update only generator
        opt_g.step()

    finally:

        # Restore discriminator
        d.requires_grad_(True)
        d.train(previous_mode)

    return loss.item()


# ============================================================
# GRADIENT FLOW CHECK
# ============================================================

def snapshot(module):

    return {
        k: v.detach().clone()
        for k, v in module.state_dict().items()
    }


def check_updates(
    g,
    d,
    real,
    labels=None
):

    opt_g = torch.optim.Adam(
        g.parameters(),
        lr=LR,
        betas=(0.5, 0.999)
    )

    opt_d = torch.optim.Adam(
        d.parameters(),
        lr=LR,
        betas=(0.5, 0.999)
    )

    before_g = {
        k: p.detach().clone()
        for k, p in g.named_parameters()
    }

    before_d = {
        k: p.detach().clone()
        for k, p in d.named_parameters()
    }

    # ----------------------------
    # D update
    # ----------------------------

    dl = discriminator_step(
        g,
        d,
        opt_g,
        opt_d,
        real,
        labels
    )

    # G must NOT change
    assert all(
        torch.equal(
            before_g[k],
            p
        )
        for k, p in g.named_parameters()
    ), "G updated in D step"

    # G should have no gradients
    assert all(
        p.grad is None
        for p in g.parameters()
    ), "Detach fakes in D step"

    # D MUST change
    assert any(
        not torch.equal(
            before_d[k],
            p
        )
        for k, p in d.named_parameters()
    ), "D did not update"

    # Snapshot discriminator
    d_state = snapshot(d)

    # ----------------------------
    # G update
    # ----------------------------

    gl = generator_step(
        g,
        d,
        opt_g,
        opt_d,
        real.size(0),
        labels
    )

    # G MUST change
    assert any(
        not torch.equal(
            before_g[k],
            p
        )
        for k, p in g.named_parameters()
    ), "G did not update"

    # D must NOT change
    assert all(
        torch.equal(
            d_state[k],
            v
        )
        for k, v in d.state_dict().items()
    ), "D changed in G step"

    # D should have no gradients
    assert all(
        p.grad is None
        for p in d.parameters()
    ), "D gradients should remain disabled"

    # Losses must be finite
    assert torch.isfinite(
        torch.tensor([dl, gl])
    ).all()

    print(
        "Update checks passed:",
        {
            "D": dl,
            "G": gl
        }
    )


# Test gradient flow
seed_all(SEED)

check_updates(
    VanillaGenerator().to(DEVICE),
    VanillaDiscriminator().to(DEVICE),
    torch.rand(
        4,
        IMG_DIM,
        device=DEVICE
    ) * 2 - 1
)


# ============================================================
# B. LOAD MNIST
# ============================================================

raw_dir = DATA_DIR / "MNIST" / "raw"
raw_dir.mkdir(
    parents=True,
    exist_ok=True
)

input_dir = (
    Path(OFFLINE_MNIST_DIR)
    if OFFLINE_MNIST_DIR is not None
    else Path("/content")
)


raw_names = [
    "train-images-idx3-ubyte",
    "train-labels-idx1-ubyte",
    "t10k-images-idx3-ubyte",
    "t10k-labels-idx1-ubyte"
]


for name in raw_names:

    destination = raw_dir / name

    if destination.exists() or not input_dir.exists():
        continue

    aliases = [
        name,
        name.replace("-idx", ".idx")
    ]

    candidates = sorted({
        path
        for alias in aliases
        for pattern in (
            alias,
            alias + ".gz"
        )
        for path in input_dir.rglob(pattern)
        if path.is_file()
    })

    if candidates:

        source = candidates[0]

        opener = (
            gzip.open
            if source.suffix == ".gz"
            else open
        )

        with opener(source, "rb") as src, \
             destination.open("wb") as dst:

            shutil.copyfileobj(
                src,
                dst
            )

        print(
            "Loaded attached file:",
            source
        )


def load_mnist(size):

    transform = transforms.Compose([

        transforms.Resize(size),

        transforms.ToTensor(),

        transforms.Normalize(
            (0.5,),
            (0.5,)
        )
    ])

    try:

        return datasets.MNIST(
            str(DATA_DIR),
            train=True,
            download=False,
            transform=transform
        )

    except RuntimeError:

        try:

            return datasets.MNIST(
                str(DATA_DIR),
                train=True,
                download=True,
                transform=transform
            )

        except Exception as exc:

            raise RuntimeError(
                "MNIST unavailable. "
                "Enable internet in Colab or supply "
                "original IDX files."
            ) from exc


def make_loader(size):

    dataset = load_mnist(size)

    limit = (
        2 * BATCH_SIZE
        if SMOKE_TEST
        else TRAIN_LIMIT
    )

    if limit is not None:

        assert (
            isinstance(limit, int)
            and limit >= 2
        ), "Use at least two examples"

        indices = torch.randperm(
            len(dataset),
            generator=torch.Generator().manual_seed(SEED)
        )

        dataset = Subset(
            dataset,
            indices[
                :min(
                    limit,
                    len(dataset)
                )
            ].tolist()
        )

    return DataLoader(
        dataset,
        batch_size=BATCH_SIZE,
        shuffle=True,
        num_workers=0,
        generator=torch.Generator().manual_seed(SEED),
        pin_memory=(DEVICE.type == "cuda")
    )


# Preview MNIST
preview_loader = make_loader(28)

real_images, real_labels = next(
    iter(preview_loader)
)

assert real_images.shape[1:] == (
    1,
    28,
    28
)

assert (
    real_images.min() >= -1
    and real_images.max() <= 1
)


plt.figure(figsize=(8, 2))

plt.imshow(
    make_grid(
        (real_images[:16] + 1) / 2,
        nrow=8
    ).permute(1, 2, 0)
)

plt.axis("off")
plt.show()

print(
    "Training examples:",
    len(preview_loader.dataset)
)


# ============================================================
# SAMPLE / PLOT FUNCTIONS
# ============================================================

@torch.no_grad()
def sample(
    g,
    noise,
    labels=None
):

    previous_mode = g.training

    g.eval()

    try:

        images = generate(
            g,
            noise,
            labels
        )

        if images.ndim == 2:

            images = images.reshape(
                -1,
                1,
                28,
                28
            )

        return (
            (images.cpu() + 1) / 2
        ).clamp(0, 1)

    finally:

        g.train(previous_mode)


def plot_grid(
    images,
    path,
    title,
    nrow=8
):

    save_image(
        images,
        path,
        nrow=nrow
    )

    fig, ax = plt.subplots(
        figsize=(
            8,
            8 if len(images) == 80 else 4
        )
    )

    ax.imshow(
        make_grid(
            images,
            nrow=nrow
        ).permute(1, 2, 0)
    )

    ax.set_title(title)
    ax.axis("off")

    plt.show()
    plt.close(fig)


# ============================================================
# EXPERIMENT RUNNER
# ============================================================

def run_experiment(
    name,
    conditional=False,
    d_lr_multiplier=1.0
):

    seed_all(SEED)

    folder = OUTPUT_DIR / name
    folder.mkdir(
        parents=True,
        exist_ok=True
    )

    # ----------------------------
    # Models
    # ----------------------------

    if conditional:

        g = (
            ConditionalGenerator()
            .to(DEVICE)
            .apply(weights_init)
        )

        d = (
            ConditionalDiscriminator()
            .to(DEVICE)
            .apply(weights_init)
        )

    else:

        g = VanillaGenerator().to(DEVICE)
        d = VanillaDiscriminator().to(DEVICE)

    # ----------------------------
    # Optimizers
    # ----------------------------

    opt_g = torch.optim.Adam(
        g.parameters(),
        lr=LR,
        betas=(0.5, 0.999)
    )

    opt_d = torch.optim.Adam(
        d.parameters(),
        lr=LR * d_lr_multiplier,
        betas=(0.5, 0.999)
    )

    # ----------------------------
    # Dataset
    # ----------------------------

    loader = make_loader(
        32 if conditional else 28
    )

    # ----------------------------
    # Epochs
    # ----------------------------

    epochs = (
        1
        if SMOKE_TEST
        else (
            CONDITIONAL_EPOCHS
            if conditional
            else BASELINE_EPOCHS
        )
    )

    # ----------------------------
    # Fixed noise
    # ----------------------------

    sample_rng = torch.Generator().manual_seed(
        SEED + 1
    )

    if conditional:

        fixed_z = torch.randn(
            8,
            LATENT_DIM,
            generator=sample_rng
        ).repeat(
            10,
            1
        ).to(DEVICE)

        fixed_y = torch.arange(
            10,
            device=DEVICE
        ).repeat_interleave(8)

    else:

        fixed_z = torch.randn(
            32,
            LATENT_DIM,
            generator=sample_rng
        ).to(DEVICE)

        fixed_y = None

    # ----------------------------
    # Save samples
    # ----------------------------

    def record(epoch):

        title = f"{name}: epoch {epoch}"

        if conditional:

            title += (
                " | requested digits "
                "0–9 from top to bottom"
            )

        plot_grid(
            sample(
                g,
                fixed_z,
                fixed_y
            ),
            folder / f"epoch_{epoch:03d}.png",
            title
        )

    record(0)

    # ----------------------------
    # Training history
    # ----------------------------

    history = {
        "d_loss": [],
        "g_loss": []
    }

    started = time.perf_counter()

    # ========================================================
    # TRAINING LOOP
    # ========================================================

    for epoch in range(
        1,
        epochs + 1
    ):

        d_total = 0
        g_total = 0
        seen = 0

        for images, labels in loader:

            images = images.to(DEVICE)

            labels = (
                labels.to(DEVICE)
                if conditional
                else None
            )

            if not conditional:

                images = images.flatten(1)

            # ------------------------
            # D update
            # ------------------------

            dl = discriminator_step(
                g,
                d,
                opt_g,
                opt_d,
                images,
                labels
            )

            # ------------------------
            # G update
            # ------------------------

            gl = generator_step(
                g,
                d,
                opt_g,
                opt_d,
                len(images),
                labels
            )

            assert torch.isfinite(
                torch.tensor(
                    [dl, gl]
                )
            ).all(), "Non-finite loss"

            d_total += dl * len(images)
            g_total += gl * len(images)

            seen += len(images)

        d_epoch_loss = d_total / seen
        g_epoch_loss = g_total / seen

        history["d_loss"].append(
            d_epoch_loss
        )

        history["g_loss"].append(
            g_epoch_loss
        )

        print(
            f"{name} "
            f"{epoch}/{epochs} | "
            f"D={d_epoch_loss:.4f} "
            f"G={g_epoch_loss:.4f}"
        )

        if (
            epoch == 1
            or epoch % 5 == 0
            or epoch == epochs
        ):

            record(epoch)

    # ========================================================
    # SAVE RESULTS
    # ========================================================

    elapsed = (
        time.perf_counter()
        - started
    )

    config = dict(

        name=name,

        conditional=conditional,

        seed=SEED,

        latent_dim=LATENT_DIM,

        num_classes=NUM_CLASSES,

        image_size=(
            32
            if conditional
            else 28
        ),

        batch_size=BATCH_SIZE,

        g_lr=LR,

        d_lr=LR * d_lr_multiplier,

        epochs=epochs,

        training_examples=len(
            loader.dataset
        ),

        smoke_test=SMOKE_TEST,

        train_limit=TRAIN_LIMIT,

        device=str(DEVICE)
    )

    torch.save(

        dict(

            generator=g.state_dict(),

            discriminator=d.state_dict(),

            optimizer_g=opt_g.state_dict(),

            optimizer_d=opt_d.state_dict(),

            config=config,

            history=history

        ),

        folder / "checkpoint.pt"
    )

    (
        folder / "results.json"
    ).write_text(

        json.dumps(
            dict(
                config=config,
                history=history,
                elapsed_seconds=elapsed
            ),
            indent=2
        )
    )

    # ----------------------------
    # Loss plot
    # ----------------------------

    fig, ax = plt.subplots(
        figsize=(8, 3)
    )

    for key, values in history.items():

        ax.plot(
            range(
                1,
                epochs + 1
            ),
            values,
            label=key
        )

    ax.set(
        xlabel="Epoch",
        ylabel="BCE loss",
        title=name
    )

    ax.legend()

    fig.tight_layout()

    fig.savefig(
        folder / "losses.png"
    )

    plt.show()
    plt.close(fig)

    return dict(

        generator=g,

        discriminator=d,

        history=history,

        folder=folder,

        config=config,

        elapsed_seconds=elapsed,

        fixed_z=fixed_z,

        fixed_y=fixed_y
    )


# ============================================================
# B. TRAIN VANILLA GAN
# ============================================================

baseline = run_experiment(
    "vanilla_baseline"
)


# ============================================================
# C. CONTROLLED INTERVENTION
# FASTER DISCRIMINATOR
# ============================================================

intervention = run_experiment(
    "vanilla_faster_d",
    d_lr_multiplier=5.0
)


# ============================================================
# COMPARE LOSS CURVES
# ============================================================

fig, axes = plt.subplots(
    1,
    2,
    figsize=(12, 3)
)


for ax, key in zip(
    axes,
    ["d_loss", "g_loss"]
):

    for label, result in [
        ("Baseline", baseline),
        ("Faster D", intervention)
    ]:

        values = result["history"][key]

        ax.plot(
            range(
                1,
                len(values) + 1
            ),
            values,
            label=label
        )

    ax.set(
        xlabel="Epoch",
        ylabel=key
    )

    ax.legend()


fig.tight_layout()

fig.savefig(
    OUTPUT_DIR /
    "intervention_losses.png"
)

plt.show()
plt.close(fig)


# ============================================================
# COMPARE FINAL SAMPLES
# ============================================================

fig, axes = plt.subplots(
    1,
    2,
    figsize=(12, 4)
)


for ax, label, result in zip(
    axes,
    ["Baseline", "Faster D"],
    [baseline, intervention]
):

    images = sample(
        result["generator"],
        baseline["fixed_z"]
    )

    ax.imshow(
        make_grid(
            images,
            nrow=8
        ).permute(1, 2, 0)
    )

    ax.set_title(label)
    ax.axis("off")


fig.tight_layout()

fig.savefig(
    OUTPUT_DIR /
    "intervention_samples.png"
)

plt.show()
plt.close(fig)


# ============================================================
# D. CONDITIONAL DCGAN
# ============================================================

# TODO D1
# One-hot encode labels and concatenate with noise.
#
# Input:
#   noise  -> (B, 100)
#   labels -> (B,)
#
# Output:
#   (B, 110, 1, 1)

def condition_noise(
    noise,
    labels
):

    # One-hot encode digit labels
    one_hot = F.one_hot(
        labels,
        num_classes=NUM_CLASSES
    ).to(dtype=noise.dtype)

    # Concatenate noise and label
    conditioned = torch.cat(
        [
            noise,
            one_hot
        ],
        dim=1
    )

    # Convert to convolutional input
    conditioned = conditioned.unsqueeze(
        -1
    ).unsqueeze(
        -1
    )

    return conditioned


# TODO D2
# One-hot encode labels, expand them spatially,
# and concatenate them with images.
#
# Input:
#   images -> (B, 1, 32, 32)
#   labels -> (B,)
#
# Output:
#   (B, 11, 32, 32)

def condition_images(
    images,
    labels
):

    # One-hot encode labels
    one_hot = F.one_hot(
        labels,
        num_classes=NUM_CLASSES
    ).to(dtype=images.dtype)

    # Shape:
    # (B, 10) -> (B, 10, 1, 1)
    one_hot = one_hot[
        :,
        :,
        None,
        None
    ]

    # Expand across image height and width
    one_hot = one_hot.expand(
        -1,
        -1,
        images.shape[2],
        images.shape[3]
    )

    # Concatenate original image
    # with class maps
    return torch.cat(
        [
            images,
            one_hot
        ],
        dim=1
    )


# ============================================================
# CONDITIONAL GENERATOR
# ============================================================

class ConditionalGenerator(nn.Module):

    def __init__(
        self,
        latent_dim=LATENT_DIM,
        num_classes=NUM_CLASSES
    ):

        super().__init__()

        self.num_classes = num_classes

        self.net = nn.Sequential(

            # 110 x 1 x 1
            nn.ConvTranspose2d(
                latent_dim + num_classes,
                256,
                4,
                1,
                0,
                bias=False
            ),

            nn.BatchNorm2d(256),
            nn.ReLU(True),

            # 256 x 4 x 4 -> 128 x 8 x 8
            nn.ConvTranspose2d(
                256,
                128,
                4,
                2,
                1,
                bias=False
            ),

            nn.BatchNorm2d(128),
            nn.ReLU(True),

            # 128 x 8 x 8 -> 64 x 16 x 16
            nn.ConvTranspose2d(
                128,
                64,
                4,
                2,
                1,
                bias=False
            ),

            nn.BatchNorm2d(64),
            nn.ReLU(True),

            # 64 x 16 x 16 -> 1 x 32 x 32
            nn.ConvTranspose2d(
                64,
                1,
                4,
                2,
                1,
                bias=False
            ),

            nn.Tanh()
        )

    def forward(
        self,
        noise,
        class_labels
    ):

        return self.net(
            condition_noise(
                noise,
                class_labels
            )
        )


# ============================================================
# CONDITIONAL DISCRIMINATOR
# ============================================================

class ConditionalDiscriminator(nn.Module):

    def __init__(
        self,
        num_classes=NUM_CLASSES
    ):

        super().__init__()

        self.num_classes = num_classes

        self.net = nn.Sequential(

            # (1 + 10) x 32 x 32
            # -> 64 x 16 x 16
            nn.Conv2d(
                in_channels=1 + num_classes,
                out_channels=64,
                kernel_size=4,
                stride=2,
                padding=1,
                bias=False
            ),

            nn.LeakyReLU(
                0.2,
                inplace=True
            ),

            # 64 x 16 x 16
            # -> 128 x 8 x 8
            nn.Conv2d(
                in_channels=64,
                out_channels=128,
                kernel_size=4,
                stride=2,
                padding=1,
                bias=False
            ),

            nn.BatchNorm2d(128),

            nn.LeakyReLU(
                0.2,
                inplace=True
            ),

            # 128 x 8 x 8
            # -> 256 x 4 x 4
            nn.Conv2d(
                in_channels=128,
                out_channels=256,
                kernel_size=4,
                stride=2,
                padding=1,
                bias=False
            ),

            nn.BatchNorm2d(256),

            nn.LeakyReLU(
                0.2,
                inplace=True
            ),

            # 256 x 4 x 4
            # -> 1 x 1 x 1
            nn.Conv2d(
                in_channels=256,
                out_channels=1,
                kernel_size=4,
                stride=1,
                padding=0,
                bias=False
            )
        )

    def forward(
        self,
        images,
        class_labels
    ):

        return self.net(
            condition_images(
                images,
                class_labels
            )
        ).flatten(1)


# ============================================================
# WEIGHT INITIALIZATION
# ============================================================

def weights_init(module):

    if isinstance(
        module,
        (
            nn.Conv2d,
            nn.ConvTranspose2d
        )
    ):

        nn.init.normal_(
            module.weight,
            0.0,
            0.02
        )

    elif isinstance(
        module,
        nn.BatchNorm2d
    ):

        nn.init.normal_(
            module.weight,
            1.0,
            0.02
        )

        nn.init.zeros_(
            module.bias
        )


# ============================================================
# TEST CONDITIONAL INPUTS
# ============================================================

seed_all(SEED)

labels = torch.tensor(
    [0, 3, 7, 9],
    device=DEVICE
)

noise = torch.randn(
    4,
    LATENT_DIM,
    device=DEVICE
)

images = (
    torch.rand(
        4,
        1,
        IMG_SIZE,
        IMG_SIZE,
        device=DEVICE
    ) * 2 - 1
)


conditioned_z = condition_noise(
    noise,
    labels
)

conditioned_x = condition_images(
    images,
    labels
)

expected = F.one_hot(
    labels,
    NUM_CLASSES
).float()


assert conditioned_z.shape == (
    4,
    LATENT_DIM + NUM_CLASSES,
    1,
    1
)

assert torch.equal(
    conditioned_z[
        :,
        :LATENT_DIM,
        0,
        0
    ],
    noise
)

assert torch.equal(
    conditioned_z[
        :,
        LATENT_DIM:,
        0,
        0
    ],
    expected
)

assert conditioned_x.shape == (
    4,
    11,
    IMG_SIZE,
    IMG_SIZE
)

assert torch.equal(
    conditioned_x[:, :1],
    images
)

assert torch.equal(
    conditioned_x[:, 1:],
    expected[
        :,
        :,
        None,
        None
    ].expand(
        -1,
        -1,
        IMG_SIZE,
        IMG_SIZE
    )
)


# ============================================================
# TEST CONDITIONAL GAN
# ============================================================

test_g = (
    ConditionalGenerator()
    .to(DEVICE)
    .apply(weights_init)
)

test_d = (
    ConditionalDiscriminator()
    .to(DEVICE)
    .apply(weights_init)
)


with torch.no_grad():

    generated = test_g(
        noise,
        labels
    )

    assert generated.shape == images.shape

    assert (
        generated.min() >= -1
        and generated.max() <= 1
    )

    assert test_d(
        generated,
        labels
    ).shape == (
        4,
        1
    )


check_updates(
    test_g,
    test_d,
    images,
    labels
)


del test_g, test_d


# ============================================================
# TRAIN CONDITIONAL DCGAN
# ============================================================

conditional = run_experiment(
    "conditional_dcgan",
    conditional=True
)


# ============================================================
# CONDITIONAL PROBES
# ============================================================

REQUESTED_DIGIT = 7

assert (
    isinstance(
        REQUESTED_DIGIT,
        int
    )
    and
    0 <= REQUESTED_DIGIT < NUM_CLASSES
)


probe_rng = torch.Generator().manual_seed(
    SEED + 2
)


# ------------------------------------------------------------
# Probe 1:
# Fixed label, varied noise
# ------------------------------------------------------------

varying_z = torch.randn(
    16,
    LATENT_DIM,
    generator=probe_rng
).to(DEVICE)

fixed_label = torch.full(
    (16,),
    REQUESTED_DIGIT,
    dtype=torch.long,
    device=DEVICE
)


plot_grid(
    sample(
        conditional["generator"],
        varying_z,
        fixed_label
    ),
    conditional["folder"] /
    f"fixed_label_{REQUESTED_DIGIT}.png",
    f"Fixed label {REQUESTED_DIGIT}, varied noise",
    nrow=4
)


# ------------------------------------------------------------
# Probe 2:
# Fixed noise, varied labels
# ------------------------------------------------------------

fixed_z = torch.randn(
    1,
    LATENT_DIM,
    generator=probe_rng
).repeat(
    10,
    1
).to(DEVICE)

varying_labels = torch.arange(
    NUM_CLASSES,
    device=DEVICE
)


plot_grid(
    sample(
        conditional["generator"],
        fixed_z,
        varying_labels
    ),
    conditional["folder"] /
    "fixed_noise.png",
    "Fixed noise; requested digits 0–9 from left to right",
    nrow=10
)


# ============================================================
# OPTIONAL: RELOAD CONDITIONAL CHECKPOINT
# ============================================================

checkpoint_path = (
    conditional["folder"] /
    "checkpoint.pt"
)

checkpoint = torch.load(
    checkpoint_path,
    map_location=DEVICE,
    weights_only=True
)


restored_g = ConditionalGenerator(
    latent_dim=checkpoint["config"]["latent_dim"],
    num_classes=checkpoint["config"]["num_classes"]
).to(DEVICE)


restored_g.load_state_dict(
    checkpoint["generator"]
)

restored_g.eval()


assert torch.allclose(
    sample(
        restored_g,
        fixed_z,
        varying_labels
    ),
    sample(
        conditional["generator"],
        fixed_z,
        varying_labels
    )
)


print(
    "Checkpoint reload verified."
)

print(
    "Artifacts saved in:",
    OUTPUT_DIR.resolve()
)


# ============================================================
# FINAL ARTIFACTS
# ============================================================

print("\nGenerated files:")

for path in sorted(
    OUTPUT_DIR.rglob("*")
):

    if path.is_file():

        print(
            path.relative_to(
                OUTPUT_DIR
            )
        )


# ============================================================
# IMPORTANT:
#
# 1. First run with:
#       SMOKE_TEST = True
#
# 2. If all checks pass, change to:
#       SMOKE_TEST = False
#
# 3. Run the notebook again for actual training.
#
# 4. For faster training in Colab:
#       Runtime -> Change runtime type -> T4 GPU
#
# 5. Main output folder:
#       /content/gan_lab_student
# ============================================================