# -*- coding: utf-8 -*-
"""Untitled62.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WbBT5AZv2eBkVt5bS6uf9S4sIzDpvp1f
"""

# ============================================================
# DENSE VARIATIONAL AUTOENCODER FOR FACES
# COMPLETE GOOGLE COLAB VERSION
# Dataset automatically downloaded from the internet
# ============================================================

# ============================================================
# 1. IMPORTS
# ============================================================

import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
from torch import nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

from torchvision import transforms

from sklearn.datasets import fetch_lfw_people
from sklearn.model_selection import train_test_split


# ============================================================
# 2. SETTINGS
# ============================================================

SEED = 42

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

DEVICE = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

IMAGE_SIZE = 45
CHANNELS = 3

INPUT_DIM = CHANNELS * IMAGE_SIZE * IMAGE_SIZE

LATENT_DIM = 100

BATCH_SIZE = 64

# Change to 3 for a quick test
EPOCHS = 10

LEARNING_RATE = 1e-3

BETA = 1.0

NUM_WORKERS = 2 if torch.cuda.is_available() else 0

print("========================================")
print("Dense Variational Autoencoder")
print("========================================")
print("Device:", DEVICE)
print("Image size:", IMAGE_SIZE)
print("Input dimension:", INPUT_DIM)
print("Latent dimension:", LATENT_DIM)
print("Batch size:", BATCH_SIZE)
print("Epochs:", EPOCHS)
print("========================================")


# ============================================================
# 3. AUTOMATICALLY DOWNLOAD LFW DATASET
# ============================================================

print("\nDownloading/loading LFW dataset...")
print("This may take a few minutes the first time.\n")

lfw = fetch_lfw_people(
    color=True,
    resize=None,
    funneled=True,
    download_if_missing=True
)

print("Dataset downloaded successfully!")
print("Number of images:", len(lfw.images))
print("Original image shape:", lfw.images.shape)


# ============================================================
# 4. PREPARE IMAGES
# ============================================================

# LFW images are normally 250 x 250 x 3.
# Convert them to 45 x 45 x 3.

images = lfw.images.astype(np.float32)

# Convert pixel values from [0,255] to [0,1]
images = images / 255.0

print("\nBefore resizing:")
print(images.shape)


# ============================================================
# 5. RESIZE IMAGES TO 45 x 45
# ============================================================

# torchvision resize expects tensors in C,H,W format

images_tensor = torch.tensor(
    images,
    dtype=torch.float32
)

images_tensor = images_tensor.permute(
    0, 3, 1, 2
)

resize_transform = transforms.Resize(
    (IMAGE_SIZE, IMAGE_SIZE)
)

images_tensor = resize_transform(
    images_tensor
)

print("After resizing:")
print(images_tensor.shape)


# ============================================================
# 6. DATASET
# ============================================================

class FaceDataset(Dataset):

    def __init__(self, images):

        self.images = images

    def __len__(self):

        return len(self.images)

    def __getitem__(self, index):

        return self.images[index]


# ============================================================
# 7. TRAIN / VALIDATION SPLIT
# ============================================================

indices = np.arange(
    len(images_tensor)
)

train_indices, val_indices = train_test_split(
    indices,
    test_size=0.2,
    random_state=SEED
)

train_images = images_tensor[
    train_indices
]

val_images = images_tensor[
    val_indices
]

train_dataset = FaceDataset(
    train_images
)

val_dataset = FaceDataset(
    val_images
)

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=NUM_WORKERS,
    pin_memory=(DEVICE.type == "cuda")
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=(DEVICE.type == "cuda")
)

print("\nTraining images:", len(train_dataset))
print("Validation images:", len(val_dataset))


# ============================================================
# 8. DISPLAY SAMPLE FACES
# ============================================================

faces = next(iter(train_loader))

print("Batch shape:", faces.shape)

fig, axes = plt.subplots(
    2,
    5,
    figsize=(10, 4)
)

for face, ax in zip(
    faces[:10],
    axes.flat
):

    ax.imshow(
        face.permute(1, 2, 0)
    )

    ax.axis("off")

plt.tight_layout()
plt.show()


# ============================================================
# 9. DENSE VAE MODEL
# ============================================================

class DenseFaceVAE(nn.Module):

    def __init__(
        self,
        input_dim=INPUT_DIM,
        latent_dim=LATENT_DIM
    ):

        super().__init__()

        self.input_dim = input_dim
        self.latent_dim = latent_dim

        # -------------------------------
        # Encoder
        # -------------------------------

        self.encoder = nn.Sequential(

            nn.Linear(
                input_dim,
                1500
            ),

            nn.ReLU(),

            nn.Linear(
                1500,
                1000
            ),

            nn.ReLU()
        )


        # -------------------------------
        # Mean and log variance heads
        # -------------------------------

        self.mu_head = nn.Linear(
            1000,
            latent_dim
        )

        self.logvar_head = nn.Linear(
            1000,
            latent_dim
        )


        # -------------------------------
        # Decoder
        # -------------------------------

        self.decoder = nn.Sequential(

            nn.Linear(
                latent_dim,
                1000
            ),

            nn.ReLU(),

            nn.Linear(
                1000,
                1500
            ),

            nn.ReLU(),

            nn.Linear(
                1500,
                input_dim
            ),

            nn.Sigmoid()
        )


    # ========================================================
    # ENCODER
    # ========================================================

    def encode(self, x):

        features = self.encoder(
            x.flatten(start_dim=1)
        )

        mu = self.mu_head(
            features
        )

        logvar = self.logvar_head(
            features
        )

        return mu, logvar


    # ========================================================
    # REPARAMETERIZATION TRICK
    # ========================================================

    def reparameterize(
        self,
        mu,
        logvar
    ):

        # std = exp(0.5 * log variance)

        std = torch.exp(
            0.5 * logvar
        )

        # Random noise

        epsilon = torch.randn_like(
            std
        )

        # Reparameterization trick

        z = mu + epsilon * std

        return z


    # ========================================================
    # DECODER
    # ========================================================

    def decode(self, z):

        pixels = self.decoder(z)

        return pixels.view(
            -1,
            CHANNELS,
            IMAGE_SIZE,
            IMAGE_SIZE
        )


    # ========================================================
    # FORWARD
    # ========================================================

    def forward(self, x):

        mu, logvar = self.encode(x)

        z = self.reparameterize(
            mu,
            logvar
        )

        reconstruction = self.decode(
            z
        )

        return reconstruction, mu, logvar


# ============================================================
# 10. CREATE MODEL
# ============================================================

model = DenseFaceVAE().to(
    DEVICE
)

print("\nModel created successfully!")

print(
    "Total parameters:",
    sum(
        p.numel()
        for p in model.parameters()
    )
)


# ============================================================
# 11. MODEL TEST
# ============================================================

test_batch = faces[:4].to(
    DEVICE
)

reconstruction, mu, logvar = model(
    test_batch
)

print("\nModel test:")
print("Input:", test_batch.shape)
print("Reconstruction:", reconstruction.shape)
print("Mu:", mu.shape)
print("Logvar:", logvar.shape)


assert reconstruction.shape == test_batch.shape

assert mu.shape == (
    4,
    LATENT_DIM
)

assert logvar.shape == (
    4,
    LATENT_DIM
)

assert reconstruction.min() >= 0
assert reconstruction.max() <= 1


# Test random sampling

z1 = model.reparameterize(
    mu,
    logvar
)

z2 = model.reparameterize(
    mu,
    logvar
)

assert not torch.equal(
    z1,
    z2
)


# Test gradients

z1.mean().backward()

assert model.mu_head.weight.grad is not None

assert model.logvar_head.weight.grad is not None

model.zero_grad(
    set_to_none=True
)

print("Model checks passed!")


# ============================================================
# 12. VAE LOSS
# ============================================================

def vae_loss(
    reconstruction,
    target,
    mu,
    logvar,
    beta=1.0
):

    # Reconstruction loss

    reconstruction_loss = F.binary_cross_entropy(
        reconstruction,
        target,
        reduction="sum"
    )


    # KL divergence

    kl_loss = -0.5 * torch.sum(
        1
        + logvar
        - mu.pow(2)
        - logvar.exp()
    )


    # Normalize by batch size

    batch_size = target.size(0)

    reconstruction_loss = (
        reconstruction_loss
        / batch_size
    )

    kl_loss = (
        kl_loss
        / batch_size
    )


    # Total VAE loss

    total_loss = (
        reconstruction_loss
        + beta * kl_loss
    )


    return (
        total_loss,
        reconstruction_loss.detach(),
        kl_loss.detach()
    )


# ============================================================
# 13. LOSS TEST
# ============================================================

dummy_x = torch.full(
    (
        2,
        3,
        45,
        45
    ),
    0.5,
    device=DEVICE
)

dummy_mu = torch.zeros(
    2,
    LATENT_DIM,
    device=DEVICE
)

dummy_logvar = torch.zeros_like(
    dummy_mu
)

total, recon_term, kl_term = vae_loss(
    dummy_x,
    dummy_x,
    dummy_mu,
    dummy_logvar
)

assert torch.isclose(
    kl_term,
    torch.tensor(
        0.0,
        device=DEVICE
    )
)


# Test gradient path

reconstruction, mu, logvar = model(
    test_batch
)

total, _, _ = vae_loss(
    reconstruction,
    test_batch,
    mu,
    logvar,
    beta=BETA
)

assert total.requires_grad

print("Loss checks passed!")


# ============================================================
# 14. TRAINING STEP
# ============================================================

def train_step(
    model,
    batch,
    optimizer,
    beta
):

    batch = batch.to(
        DEVICE,
        non_blocking=True
    )

    optimizer.zero_grad(
        set_to_none=True
    )

    reconstruction, mu, logvar = model(
        batch
    )

    total_loss, reconstruction_loss, kl_loss = vae_loss(
        reconstruction,
        batch,
        mu,
        logvar,
        beta
    )

    total_loss.backward()

    optimizer.step()

    return (
        total_loss.item(),
        reconstruction_loss.item(),
        kl_loss.item()
    )


# ============================================================
# 15. VALIDATION
# ============================================================

@torch.no_grad()
def evaluate(
    model,
    loader,
    beta
):

    model.eval()

    totals = np.zeros(
        3,
        dtype=np.float64
    )

    examples = 0

    for batch in loader:

        batch = batch.to(
            DEVICE,
            non_blocking=True
        )

        reconstruction, mu, logvar = model(
            batch
        )

        values = vae_loss(
            reconstruction,
            batch,
            mu,
            logvar,
            beta
        )

        batch_size = batch.size(0)

        totals += np.array([
            value.item()
            for value in values
        ]) * batch_size

        examples += batch_size

    return totals / examples


# ============================================================
# 16. TRAIN
# ============================================================

model = DenseFaceVAE().to(
    DEVICE
)

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=LEARNING_RATE
)

history = {
    "train_total": [],
    "val_total": [],
    "val_reconstruction": [],
    "val_kl": []
}


print("\n========================================")
print("STARTING TRAINING")
print("========================================")


for epoch in range(
    1,
    EPOCHS + 1
):

    model.train()

    running_total = 0.0

    seen = 0


    for batch in train_loader:

        total, reconstruction_term, kl_term = train_step(
            model,
            batch,
            optimizer,
            BETA
        )

        running_total += (
            total * batch.size(0)
        )

        seen += batch.size(0)


    # Validation

    (
        val_total,
        val_reconstruction,
        val_kl
    ) = evaluate(
        model,
        val_loader,
        BETA
    )


    train_total = (
        running_total / seen
    )


    history["train_total"].append(
        train_total
    )

    history["val_total"].append(
        val_total
    )

    history["val_reconstruction"].append(
        val_reconstruction
    )

    history["val_kl"].append(
        val_kl
    )


    print(
        f"Epoch {epoch:02d} | "
        f"Train {train_total:.2f} | "
        f"Val {val_total:.2f} | "
        f"Recon {val_reconstruction:.2f} | "
        f"KL {val_kl:.2f}"
    )


print("\n========================================")
print("TRAINING COMPLETE")
print("========================================")


# ============================================================
# 17. TRAINING GRAPH
# ============================================================

plt.figure(
    figsize=(8, 5)
)

plt.plot(
    history["train_total"],
    label="Train Total"
)

plt.plot(
    history["val_total"],
    label="Validation Total"
)

plt.xlabel("Epoch")
plt.ylabel("Negative ELBO per Image")

plt.title(
    "VAE Training Curve"
)

plt.legend()

plt.grid(True)

plt.show()


# ============================================================
# 18. RECONSTRUCTION + KL GRAPH
# ============================================================

plt.figure(
    figsize=(8, 5)
)

plt.plot(
    history["val_reconstruction"],
    label="Validation Reconstruction"
)

plt.plot(
    history["val_kl"],
    label="Validation KL"
)

plt.xlabel("Epoch")
plt.ylabel("Loss")

plt.title(
    "Validation Reconstruction and KL"
)

plt.legend()

plt.grid(True)

plt.show()


# ============================================================
# 19. RECONSTRUCT FACES
# ============================================================

model.eval()

validation_faces = next(
    iter(val_loader)
)[:8].to(DEVICE)


with torch.no_grad():

    # Use posterior mean
    mu, _ = model.encode(
        validation_faces
    )

    reconstructed_faces = model.decode(
        mu
    )


originals = validation_faces.cpu()

reconstructed_faces = (
    reconstructed_faces.cpu()
)


fig, axes = plt.subplots(
    2,
    8,
    figsize=(16, 4)
)


for i in range(8):

    axes[0, i].imshow(
        originals[i].permute(
            1,
            2,
            0
        )
    )

    axes[1, i].imshow(
        reconstructed_faces[i]
        .permute(1, 2, 0)
        .clamp(0, 1)
    )

    axes[0, i].axis("off")
    axes[1, i].axis("off")


axes[0, 0].set_ylabel(
    "Original"
)

axes[1, 0].set_ylabel(
    "Reconstructed"
)

plt.tight_layout()

plt.show()


# ============================================================
# 20. GENERATE NEW FACES
# ============================================================

model.eval()

with torch.no_grad():

    # Sample z from N(0,I)

    z = torch.randn(
        10,
        LATENT_DIM,
        device=DEVICE
    )

    generated_faces = model.decode(
        z
    )


assert generated_faces.shape == (
    10,
    3,
    45,
    45
)


# Display generated faces

fig, axes = plt.subplots(
    2,
    5,
    figsize=(10, 4)
)


for face, ax in zip(
    generated_faces.cpu(),
    axes.flat
):

    ax.imshow(
        face.permute(
            1,
            2,
            0
        ).clamp(0, 1)
    )

    ax.axis("off")


plt.tight_layout()

plt.show()


# ============================================================
# 21. SAVE MODEL
# ============================================================

torch.save(
    model.state_dict(),
    "/content/dense_face_vae.pth"
)

print(
    "\nModel saved as:"
)

print(
    "/content/dense_face_vae.pth"
)


# ============================================================
# 22. CONCEPTUAL ANSWERS
# ============================================================

print("""
============================================================
LAB ANSWERS
============================================================

1. SHAPES

For a batch of N images:

mu:
    (N, 100)

logvar:
    (N, 100)

z:
    (N, 100)


2. WHY NO RELU ON MU AND LOGVAR?

Both mu and logvar need to represent arbitrary real numbers.
Using ReLU would restrict the outputs to non-negative values.

Therefore the final probabilistic heads do not use ReLU.


3. WHY REPARAMETERIZATION?

Direct sampling introduces a stochastic operation that makes
ordinary backpropagation through the encoder difficult.

The reparameterization trick uses:

    z = mu + std * epsilon

where epsilon is random noise.

This allows gradients to flow through mu and logvar.


4. WHAT HAPPENS WHEN BETA = 0?

The KL-divergence term is removed from the objective.

The model is therefore not encouraged to make its latent
distribution close to N(0,I).

As a result, sampling directly from N(0,I) can produce
poor-quality faces.


5. WHAT HAPPENS WHEN BETA INCREASES?

A larger beta gives more importance to the KL term.

This pushes the latent distribution closer to the
unit-normal prior.

However, stronger regularization can reduce reconstruction
fidelity.


6. WHY DOES A VAE NOT NEED CONVOLUTION?

The essential parts of a VAE are:

- probabilistic encoder
- mu and logvar
- reparameterization
- decoder
- reconstruction loss
- KL-divergence loss

None of these require convolutional layers.

The disadvantage of a dense network is that images are
flattened into vectors, so spatial relationships are not
represented explicitly. This can result in less efficient
image processing and blurrier reconstructions.

============================================================
LAB COMPLETE
============================================================
""")